apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: serve-demo-cluster
  region: us-west-2

managedNodeGroups:
  - name: managed-ng-1
    instanceType: m5.2xlarge
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    volumeSize: 100
